-- 코드를 입력하세요
SELECT '/home/grep/src/'||b.BOARD_ID||'/'||FILE_ID||FILE_NAME||FILE_EXT as FILE_PATH
FROM USED_GOODS_BOARD b, USED_GOODS_FILE f
WHERE b.BOARD_ID = f.BOARD_ID
      AND VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY f.FILE_ID desc;